import type { Metadata } from 'next'
import { cookies } from 'next/headers'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from '@/components/Header'
import ThemeProvider from '@/components/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Daniel Tea',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const savedTheme =
    cookieStore.get('theme')?.value === 'dark' ? 'dark' : 'light'

  return (
    <html
      lang="en"
      className={savedTheme === 'dark' ? 'dark' : undefined}
      suppressHydrationWarning
    >
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme={savedTheme}
          enableSystem={false}
        >
          <main className="container p-4 md:p-16 print:p-12">
            <Header></Header>
            <hr className="border-border mx-auto my-4 w-full max-w-2xl"></hr>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
