import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Daniel Tea',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container p-4 print:p-12 md:p-16">
          <Header></Header>
          <hr className="border-zinc-400 my-4 mx-auto w-full max-w-2xl"></hr>
          {children}
        </main>
      </body>
    </html>
  )
}
